import express, { Request, Response, NextFunction } from "express";
import path from "path";
import dns from "dns";
import jwt from "jsonwebtoken";
import nodemailer from "nodemailer";
import db from "./db";
import { User, UserRole, Applicant, ServiceRequest, Notice, ActivityLog, SystemSettings } from "./src/types";

// Setup DNS caching fallback to prevent timeout bugs inside container envs
dns.setDefaultResultOrder?.("ipv4first");

const app = express();
const PORT = 3000;
const JWT_SECRET = process.env.JWT_SECRET || "NS_MANPOWER_SECRET_KEY_JWT_2026";

// SMTP Email dispatcher helper
async function sendNotificationEmail(subject: string, htmlContent: string) {
  try {
    const settings = db.getSettings();
    if (!settings.smtp_host || !settings.smtp_user || !settings.smtp_pass) {
      console.log("⚠️ SMTP not configured on backend. Skipping email dispatch for:", subject);
      return;
    }

    const host = settings.smtp_host;
    const port = Number(settings.smtp_port) || 587;
    const secure = settings.smtp_secure ?? (port === 465);
    const user = settings.smtp_user;
    const pass = settings.smtp_pass;
    const senderName = settings.smtp_sender_name || settings.company_name || "Nirapotta & Seba Manpower Provider Ltd.";
    const senderEmail = settings.smtp_sender_email || settings.email || "noreply@exprogroupbd.com";
    
    // Fallback recipient to the system email if none specific are added
    const recipeList = settings.smtp_recipient_emails
      ? settings.smtp_recipient_emails.split(",").map(e => e.trim()).filter(Boolean)
      : [settings.email || "info@exprogroupbd.com"].filter(Boolean);

    if (recipeList.length === 0) {
      console.log("⚠️ No recipient list is configured. Skipping email dispatch.");
      return;
    }

    const transporter = nodemailer.createTransport({
      host,
      port,
      secure,
      auth: { user, pass },
      tls: {
         rejectUnauthorized: false // allows self-signed dev boxes
      }
    });

    const info = await transporter.sendMail({
      from: `"${senderName}" <${senderEmail}>`,
      to: recipeList.join(", "),
      subject,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; border: 1px solid #e2e8f0; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.05);">
          <div style="background-color: #183A72; color: #ffffff; padding: 20px; text-align: center;">
            <h1 style="margin: 0; font-size: 20px; font-weight: 600; font-family: 'Plus Jakarta Sans', sans-serif;">${senderName}</h1>
            <p style="margin: 4px 0 0 0; font-size: 13px; opacity: 0.85;">Operational Security & Resource Dispatch Alerts</p>
          </div>
          <div style="padding: 24px; background-color: #ffffff; color: #1e293b; line-height: 1.6;">
            ${htmlContent}
          </div>
          <div style="padding: 16px; background-color: #f8fafc; border-top: 1px solid #e2e8f0; text-align: center; font-size: 11px; color: #64748b;">
            <p style="margin: 0;">This email is automatically generated by the Nirapotta & Seba Admin Engine.</p>
            <p style="margin: 4px 0 0 0;">Banani Office Complex, Dhaka, Bangladesh.</p>
          </div>
        </div>
      `
    });

    console.log("📨 SMTP Notification delivered successfully:", info.messageId, "To:", recipeList);
  } catch (err) {
    console.error("❌ Failed to broadcast SMTP notification:", err);
  }
}

// User-Agent parser for security auditing
function parseUserAgent(uaStr: string = ""): { browser: string; device: string } {
  let browser = "Web Browser";
  let device = "Desktop Windows/Linux";
  const ua = uaStr.toLowerCase();

  if (ua.includes("firefox")) browser = "Firefox";
  else if (ua.includes("chrome") && !ua.includes("safari")) browser = "Chrome";
  else if (ua.includes("chrome") && ua.includes("safari")) browser = "Chrome / Safari";
  else if (ua.includes("safari") && !ua.includes("chrome")) browser = "Safari";
  else if (ua.includes("edge") || ua.includes("edg/")) browser = "Microsoft Edge";
  else if (ua.includes("opr") || ua.includes("opera")) browser = "Opera";

  if (ua.includes("iphone") || ua.includes("ipod")) device = "Apple iPhone";
  else if (ua.includes("ipad")) device = "Apple iPad";
  else if (ua.includes("android")) {
    if (ua.includes("mobile")) device = "Android Mobile Phone";
    else device = "Android Tablet";
  } else if (ua.includes("macintosh")) device = "Apple Mac Notebook";
  else if (ua.includes("windows")) device = "Microsoft Windows PC";
  else if (ua.includes("linux")) device = "Linux Workstation";

  return { browser, device };
}

// Middlewares
app.use(express.json({ limit: "25mb" }));
app.use(express.urlencoded({ extended: true, limit: "25mb" }));

// Express Custom Request Interface for Authentication Context
interface AuthenticatedRequest extends Request {
  user?: {
    id: string;
    name: string;
    email: string;
    role: UserRole;
  };
}

// Authentication Middleware
const authenticateToken = (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
  const authHeader = req.headers["authorization"];
  const token = authHeader && authHeader.split(" ")[1];

  if (!token) {
    res.status(401).json({ error: "Access token is required" });
    return;
  }

  jwt.verify(token, JWT_SECRET, (err, decoded) => {
    if (err) {
      res.status(403).json({ error: "Invalid or expired session token" });
      return;
    }
    req.user = decoded as { id: string; name: string; email: string; role: UserRole };
    next();
  });
};

// RBAC Guard
const requireRole = (allowedRoles: UserRole[]) => {
  return (req: AuthenticatedRequest, res: Response, next: NextFunction) => {
    if (!req.user) {
      res.status(401).json({ error: "Unauthorized" });
      return;
    }

    if (!allowedRoles.includes(req.user.role)) {
      res.status(403).json({ error: "Access denied. Insufficient privileges." });
      return;
    }

    next();
  };
};

/* ==========================================================================
   PUBLIC API ENDPOINTS
   ========================================================================== */

// 1. Get Live settings (Language switcher configurations, office numbers)
app.get("/api/public/settings", (req: Request, res: Response) => {
  try {
    const settings = db.getSettings();
    res.json(settings);
  } catch (error) {
    res.status(500).json({ error: "Failed to load public settings" });
  }
});

// 2. Try simple diagnostic server health route
app.get("/api/public/health", (req: Request, res: Response) => {
  res.json({ status: "healthy", timestamp: new Date().toISOString() });
});

// 3. Get published notices for the notice board
app.get("/api/public/notices", (req: Request, res: Response) => {
  try {
    const notices = db.getNotices()
      .filter((n) => n.status === "published")
      .sort((a, b) => {
        // Pinned notices go to the top
        if (a.is_pinned && !b.is_pinned) return -1;
        if (!a.is_pinned && b.is_pinned) return 1;
        // Then sort by date (newest first)
        return new Date(b.published_date).getTime() - new Date(a.published_date).getTime();
      });
    res.json(notices);
  } catch (error) {
    res.status(500).json({ error: "Failed to fetch notices" });
  }
});

// 4. Get approved personnel/listings (helpers, security guards, pickup drivers)
app.get("/api/public/applicants", (req: Request, res: Response) => {
  try {
    const { category } = req.query;
    let list = db.getApplicants().filter((a) => a.status === "approved");

    if (category) {
      list = list.filter((a) => a.category === category);
    }

    res.json(list);
  } catch (error) {
    res.status(500).json({ error: "Failed to load service listings" });
  }
});

// 5. Get a specific approved personnel profile details
app.get("/api/public/applicants/:id", (req: Request, res: Response) => {
  try {
    const applicant = db.getApplicantById(req.params.id);
    if (!applicant || applicant.status !== "approved") {
      res.status(404).json({ error: "Profile not found or not yet approved" });
      return;
    }
    res.json(applicant);
  } catch (error) {
    res.status(500).json({ error: "Failed to load details" });
  }
});

// 6. Submit a Worker Application
app.post("/api/public/apply", (req: Request, res: Response) => {
  try {
    const {
      full_name, father_name, mother_name, dob, nid, phone, email, address,
      category, experience, skills, photo, documents,
      helper_type, security_type, location,
      vehicle_type, vehicle_photo, route, capacity, schedule, area, description
    } = req.body;

    if (!full_name || !phone || !nid || !category) {
      res.status(400).json({ error: "Full Name, Phone Number, National ID, and Category are required." });
      return;
    }

    // Process Date of Birth to calculate Age
    let ageComputed = 25; // fallback
    if (dob) {
      const birthDate = new Date(dob);
      const difference = Date.now() - birthDate.getTime();
      const ageDate = new Date(difference);
      ageComputed = Math.abs(ageDate.getUTCFullYear() - 1970);
    }

    const newApplicant: Applicant = {
      id: "app_" + Math.random().toString(36).substr(2, 9),
      full_name,
      father_name: father_name || "N/A",
      mother_name: mother_name || "N/A",
      dob: dob || "1995-01-01",
      age: ageComputed,
      nid,
      phone,
      email: email || "",
      address: address || "N/A",
      category,
      experience: experience || "Fresher",
      skills: skills || "",
      photo: photo || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400",
      documents: documents || "NID Verification pending",
      status: "pending", // Always pending initially
      created_at: new Date().toISOString(),
      helper_type,
      security_type,
      location: location || "Dhaka",
      vehicle_type,
      vehicle_photo: vehicle_photo || "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
      route,
      capacity: capacity ? Number(capacity) : undefined,
      schedule,
      area: area || location || "Dhaka",
      description: description || ""
    };

    const saved = db.addApplicant(newApplicant);
    
    // Log user activity
    db.addActivityLog({
      id: "log_" + Math.random().toString(36).substr(2, 9),
      user_id: "public",
      user_name: "Visitor Form",
      action: `New candidate application submitted online: ${full_name} (${category})`,
      created_at: new Date().toISOString()
    });

    // SMTP dispatch on registration
    const settings = db.getSettings();
    if (settings.notify_new_candidate !== false) {
      sendNotificationEmail(
        `[Portal Alert] New Candidate Applied: ${full_name}`,
        `<h2>New Manpower Registration Received</h2>
         <p>A new worker has applied online and is awaiting administrative screening.</p>
         <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold; width: 150px;">Full Name:</td><td style="padding: 8px;">${full_name}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Category:</td><td style="padding: 8px; text-transform: capitalize;">${category}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Experience:</td><td style="padding: 8px;">${experience}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Phone Number:</td><td style="padding: 8px;">${phone}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Location:</td><td style="padding: 8px;">${location || "Dhaka"}</td></tr>
         </table>
         <p>Verify records and documents in the Admin Panel to approve this candidate.</p>`
      );
    }

    res.status(201).json({ success: true, applicant: saved });
  } catch (error) {
    res.status(500).json({ error: "Failed to submit application. Please check input formats." });
  }
});

// 7. Submit a Customer Service Request
app.post("/api/public/request", (req: Request, res: Response) => {
  try {
    const { customer_name, phone, email, address, service_type, duration, budget, notes } = req.body;

    if (!customer_name || !phone || !service_type || !address) {
      res.status(400).json({ error: "Name, Phone Number, Service Type, and Address are required." });
      return;
    }

    const newRequest: ServiceRequest = {
      id: "req_" + Math.random().toString(36).substr(2, 9),
      customer_name,
      phone,
      email: email || "",
      address,
      service_type,
      duration: duration || "1 Month",
      budget: budget || "Negotiable",
      notes: notes || "",
      status: "new",
      created_at: new Date().toISOString()
    };

    const saved = db.addServiceRequest(newRequest);

    db.addActivityLog({
      id: "log_" + Math.random().toString(36).substr(2, 9),
      user_id: "public",
      user_name: "Visitor Form",
      action: `New service request placed by customer: ${customer_name} for ${service_type}`,
      created_at: new Date().toISOString()
    });

    // SMTP dispatch on service order
    const settings = db.getSettings();
    if (settings.notify_new_request !== false) {
      sendNotificationEmail(
        `[Portal Alert] New Service Order: ${customer_name}`,
        `<h2>New Customer Service Booking</h2>
         <p>A client has requested manpower staffing details.</p>
         <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold; width: 150px;">Client Name:</td><td style="padding: 8px;">${customer_name}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Service Field:</td><td style="padding: 8px;">${service_type}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Duration Contract:</td><td style="padding: 8px;">${duration}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Indicated Budget:</td><td style="padding: 8px;">${budget}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Contact Details:</td><td style="padding: 8px;">${phone} / ${email || "No Email"}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Site Address:</td><td style="padding: 8px;">${address}</td></tr>
         </table>
         <blockquote style="background: #f1f5f9; padding: 12px; border-left: 4px solid #183a72; margin: 10px 0; font-style: italic;"><strong>Customer Notes:</strong><br />${notes || "None"}</blockquote>`
      );
    }

    res.status(201).json({ success: true, request: saved });
  } catch (error) {
    res.status(500).json({ error: "Failed to save request" });
  }
});

// 8. Secure Admin Login Endpoint
app.post("/api/auth/login", (req: Request, res: Response) => {
  try {
    const { email, password } = req.body;

    if (!email || !password) {
      res.status(400).json({ error: "Email and password are required" });
      return;
    }

    const user = db.getUserByEmail(email);
    if (!user) {
      res.status(401).json({ error: "Account with this email does not exist" });
      return;
    }

    const isMatch = db.verifyPassword(user.id, password);
    if (!isMatch) {
      res.status(401).json({ error: "Incorrect password. Please try again." });
      return;
    }

    // Sign JWT
    const token = jwt.sign(
      { id: user.id, name: user.name, email: user.email, role: user.role },
      JWT_SECRET,
      { expiresIn: "24h" }
    );

    // Detect device change signature
    const userAgent = req.headers["user-agent"] || "";
    const { browser, device } = parseUserAgent(userAgent);
    const rawIp = (req.headers["x-forwarded-for"] as string)?.split(",")[0] || req.ip || "127.0.0.1";
    const ip = rawIp === "::1" || rawIp === "::ffff:127.0.0.1" ? "127.0.0.1" : rawIp;
    const location = ip === "127.0.0.1" ? "Local Developer Instance / Loopback" : "Incoming Gateway, Dhaka";
    const signature = `${browser} on ${device} (IP: ${ip})`;

    const knownDevices = (user as any).known_devices || [];
    const isNewDevice = !knownDevices.includes(signature);

    if (isNewDevice) {
      // Register device security flag
      (user as any).known_devices = [...knownDevices, signature];
      
      // Save alert log
      db.addActivityLog({
        id: "log_" + Math.random().toString(36).substr(2, 9),
        user_id: user.id,
        user_name: user.name,
        action: `🚨 SECURITY ALERT: Login initiated from anomalous terminal / browser user-agent: ${signature}`,
        created_at: new Date().toISOString()
      });

      const settings = db.getSettings();
      if (settings.notify_security_alerts !== false) {
        sendNotificationEmail(
          `🚨 Security Notice: New Device Login Alert`,
          `<h3>Security Access Alert</h3>
           <p>An administrative user session has logged in from an unrecognized terminal environment or browser user-agent signature.</p>
           <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
             <tr style="background-color: #fef2f2;"><td style="padding: 8px; font-weight: bold; width: 150px; color: #ef4444;">Account:</td><td style="padding: 8px; font-weight: bold;">${user.name} (${user.email})</td></tr>
             <tr><td style="padding: 8px; font-weight: bold;">Assigned Role:</td><td style="padding: 8px; text-transform: uppercase;">${user.role}</td></tr>
             <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Browser:</td><td style="padding: 8px;">${browser}</td></tr>
             <tr><td style="padding: 8px; font-weight: bold;">Device Platform:</td><td style="padding: 8px;">${device}</td></tr>
             <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Client Net IP:</td><td style="padding: 8px;">${ip}</td></tr>
             <tr><td style="padding: 8px; font-weight: bold;">Est. Location:</td><td style="padding: 8px;">${location}</td></tr>
           </table>
           <p style="font-size: 12px; color: #64748b; font-style: italic;">If this logon was completed by you, no action is requested. If this session was unauthorized, revoke this password instantly.</p>`
        );
      }
    } else {
      // Normal activity login log
      db.addActivityLog({
        id: "log_" + Math.random().toString(36).substr(2, 9),
        user_id: user.id,
        user_name: user.name,
        action: `User logged in securely (${user.role}) on trusted terminal/dev: ${browser} / ${device}`,
        created_at: new Date().toISOString()
      });
    }

    db.save();

    res.json({
      success: true,
      token,
      user: {
        id: user.id,
        name: user.name,
        email: user.email,
        role: user.role
      }
    });
  } catch (error) {
    res.status(500).json({ error: "System login processing error" });
  }
});

/* ==========================================================================
   SECURE ADMIN DASHBOARD ROUTING (AUTHENTICATED)
   ========================================================================== */

// Verify session authenticity
app.get("/api/auth/me", authenticateToken, (req: AuthenticatedRequest, res: Response) => {
  res.json({ user: req.user });
});

// 1. Diagnostics & Stats Card Values
app.get("/api/admin/stats", authenticateToken, (req: AuthenticatedRequest, res: Response) => {
  try {
    const applicants = db.getApplicants();
    const requests = db.getServiceRequests();
    const notices = db.getNotices();

    const stats = {
      totalApplicants: applicants.length,
      approvedApplicants: applicants.filter((a) => a.status === "approved").length,
      pendingApplicants: applicants.filter((a) => a.status === "pending").length,
      rejectedApplicants: applicants.filter((a) => a.status === "rejected").length,
      totalRequests: requests.length,
      requestStatusNew: requests.filter((r) => r.status === "new").length,
      requestStatusInProgress: requests.filter((r) => r.status === "in_progress").length,
      requestStatusCompleted: requests.filter((r) => r.status === "completed").length,
      requestStatusCancelled: requests.filter((r) => r.status === "cancelled").length,
      totalNotices: notices.length,
      categoryDistribution: {
        helper: applicants.filter((a) => a.category === "helper").length,
        security: applicants.filter((a) => a.category === "security").length,
        pickup: applicants.filter((a) => a.category === "pickup").length,
      },
    };

    res.json(stats);
  } catch (error) {
    res.status(500).json({ error: "Failed to compile admin stats" });
  }
});

// 2. Applicant Management API Route
app.get("/api/applicants", authenticateToken, (req: AuthenticatedRequest, res: Response) => {
  res.json(db.getApplicants());
});

app.get("/api/users", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  res.json(db.getUsers());
});

app.put("/api/applicants/:id", authenticateToken, requireRole(["super_admin", "admin", "editor"]), (req: AuthenticatedRequest, res: Response) => {
  const applicantId = req.params.id;
  const updates = req.body;

  // Let's implement Editor boundaries (RBAC): Editors cannot delete, but can edit
  const applicant = db.getApplicantById(applicantId);
  if (!applicant) {
    res.status(404).json({ error: "Candidate profile not found" });
    return;
  }

  const formerStatus = applicant.status;
  const updated = db.updateApplicant(applicantId, updates);
  
  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `Updated applicant profile ${applicant.full_name} (Status to: ${updates.status || applicant.status})`,
    created_at: new Date().toISOString()
  });

  if (updated && updates.status && updates.status !== formerStatus) {
    const settings = db.getSettings();
    if (settings.notify_candidate_status !== false) {
      sendNotificationEmail(
        `[Portal Alert] Candidate status changed to: ${updated.status}`,
        `<h2>Candidate Verification Status Updated</h2>
         <p>An administrator has audited candidate records and modified their listing status.</p>
         <table style="width: 100%; border-collapse: collapse; margin: 15px 0;">
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold; width: 150px;">Candidate Name:</td><td style="padding: 8px;">${updated.full_name}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold;">Category:</td><td style="padding: 8px; text-transform: capitalize;">${updated.category}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Previous Status:</td><td style="padding: 8px; text-transform: uppercase; color: #64748b;">${formerStatus}</td></tr>
           <tr><td style="padding: 8px; font-weight: bold; color: #183a72;">New Status:</td><td style="padding: 8px; text-transform: uppercase; font-weight: bold; color: ${updated.status === "approved" ? "#10b981" : updated.status === "rejected" ? "#ef4444" : "#f59e0b"};">${updated.status}</td></tr>
           <tr style="background-color: #f8fafc;"><td style="padding: 8px; font-weight: bold;">Audited By:</td><td style="padding: 8px;">${req.user!.name} (${req.user!.role})</td></tr>
         </table>`
      );
    }
  }

  res.json({ success: true, applicant: updated });
});

app.delete("/api/applicants/:id", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  const applicant = db.getApplicantById(req.params.id);
  if (!applicant) {
    res.status(404).json({ error: "Candidate not found" });
    return;
  }

  db.deleteApplicant(req.params.id);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `Deleted candidate application: ${applicant.full_name}`,
    created_at: new Date().toISOString()
  });

  res.json({ success: true });
});

// 3. Customer Service Request Management API
app.get("/api/requests", authenticateToken, (req: AuthenticatedRequest, res: Response) => {
  res.json(db.getServiceRequests());
});

app.put("/api/requests/:id", authenticateToken, requireRole(["super_admin", "admin", "editor"]), (req: AuthenticatedRequest, res: Response) => {
  const requestId = req.params.id;
  const updates = req.body;

  const request = db.getServiceRequestById(requestId);
  if (!request) {
    res.status(404).json({ error: "Service request not found" });
    return;
  }

  const updated = db.updateServiceRequest(requestId, updates);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `Updated Service Request or assigned a worker for ${request.customer_name}. Status: ${updates.status || request.status}`,
    created_at: new Date().toISOString()
  });

  res.json({ success: true, request: updated });
});

app.delete("/api/requests/:id", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  const request = db.getServiceRequestById(req.params.id);
  if (!request) {
    res.status(404).json({ error: "Request not found" });
    return;
  }

  db.deleteServiceRequest(req.params.id);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `Deleted customer request from ${request.customer_name}`,
    created_at: new Date().toISOString()
  });

  res.json({ success: true });
});

// 4. Notice CRUD Operations
app.get("/api/notices", authenticateToken, (req: AuthenticatedRequest, res: Response) => {
  res.json(db.getNotices());
});

app.post("/api/notices", authenticateToken, requireRole(["super_admin", "admin", "editor"]), (req: AuthenticatedRequest, res: Response) => {
  try {
    const { title, content, priority, status, is_pinned } = req.body;
    if (!title || !content) {
      res.status(400).json({ error: "Title and content are required" });
      return;
    }

    const newNotice: Notice = {
      id: "notice_" + Math.random().toString(36).substr(2, 9),
      title,
      content,
      priority: priority || "normal",
      status: status || "draft",
      is_pinned: !!is_pinned,
      published_date: new Date().toISOString(),
      created_at: new Date().toISOString()
    };

    const saved = db.addNotice(newNotice);

    db.addActivityLog({
      id: "log_" + Math.random().toString(36).substr(2, 9),
      user_id: req.user!.id,
      user_name: req.user!.name,
      action: `Created new notice board entry: ${title} (${status})`,
      created_at: new Date().toISOString()
    });

    // Notify if notice is published immediately
    if (saved && saved.status === "published") {
      const settings = db.getSettings();
      if (settings.notify_notice_published !== false) {
        sendNotificationEmail(
          `[Notice Published] ${saved.title}`,
          `<h2>New Notice Board Entry Published</h2>
           <p>An administrative user session has posted a new notice for public viewing.</p>
           <blockquote style="background: #f1f5f9; padding: 12px; border-left: 4px solid #183a72; margin: 15px 0;">
             <strong style="display: block; margin-bottom: 6px;">${saved.title}</strong>
             ${saved.content}
           </blockquote>
           <p>Priority level: <span style="text-transform: uppercase; font-weight: bold; color: ${saved.priority === "high" ? "#ef4444" : "#183a72"};">${saved.priority}</span></p>`
        );
      }
    }

    res.status(201).json({ success: true, notice: saved });
  } catch (error) {
    res.status(500).json({ error: "Failed to publish notice" });
  }
});

app.put("/api/notices/:id", authenticateToken, requireRole(["super_admin", "admin", "editor"]), (req: AuthenticatedRequest, res: Response) => {
  const noticeId = req.params.id;
  const updates = req.body;

  const notice = db.getNoticeById(noticeId);
  if (!notice) {
    res.status(404).json({ error: "Notice entry not found" });
    return;
  }

  const formerStatus = notice.status;
  const updated = db.updateNotice(noticeId, updates);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `Edited Notice entry: ${notice.title}`,
    created_at: new Date().toISOString()
  });

  // Notify if status transitioned to published
  if (updated && updated.status === "published" && formerStatus !== "published") {
    const settings = db.getSettings();
    if (settings.notify_notice_published !== false) {
      sendNotificationEmail(
        `[Notice Published] ${updated.title}`,
        `<h2>Draft Notice Published</h2>
         <p>A previously saved notice has been reviewed and published live.</p>
         <blockquote style="background: #f1f5f9; padding: 12px; border-left: 4px solid #183a72; margin: 15px 0;">
           <strong style="display: block; margin-bottom: 6px;">${updated.title}</strong>
           ${updated.content}
         </blockquote>`
      );
    }
  }

  res.json({ success: true, notice: updated });
});

app.delete("/api/notices/:id", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  const notice = db.getNoticeById(req.params.id);
  if (!notice) {
    res.status(404).json({ error: "Notice entry not found" });
    return;
  }

  db.deleteNotice(req.params.id);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: `De-registered Notice entry: ${notice.title}`,
    created_at: new Date().toISOString()
  });

  res.json({ success: true });
});

// 5. Audit Activity Logs Endpoint
app.get("/api/logs", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  res.json(db.getActivityLogs());
});

// 6. Config Settings PUT endpoint
app.put("/api/settings", authenticateToken, requireRole(["super_admin", "admin"]), (req: AuthenticatedRequest, res: Response) => {
  const updates = req.body;
  const updatedSettings = db.updateSettings(updates);

  db.addActivityLog({
    id: "log_" + Math.random().toString(36).substr(2, 9),
    user_id: req.user!.id,
    user_name: req.user!.name,
    action: "Updated system website, SMTP, SEO configuration, and metadata settings.",
    created_at: new Date().toISOString()
  });

  res.json({ success: true, settings: updatedSettings });
});

// 7. Secure Admin Manual Candidate Enrollment Endpoint
app.post("/api/admin/applicants", authenticateToken, requireRole(["super_admin", "admin", "editor"]), (req: AuthenticatedRequest, res: Response) => {
  try {
    const {
      full_name, father_name, mother_name, dob, nid, phone, email, address,
      category, experience, skills, photo, documents, status,
      helper_type, security_type, location,
      vehicle_type, vehicle_photo, route, capacity, schedule, area, description
    } = req.body;

    if (!full_name || !phone || !nid || !category) {
      res.status(400).json({ error: "Full Name, Phone Number, National ID, and Category are required." });
      return;
    }

    let ageComputed = 25;
    if (dob) {
      const birthDate = new Date(dob);
      const difference = Date.now() - birthDate.getTime();
      const ageDate = new Date(difference);
      ageComputed = Math.abs(ageDate.getUTCFullYear() - 1970);
    }

    const newApplicant: Applicant = {
      id: "app_" + Math.random().toString(36).substr(2, 9),
      full_name,
      father_name: father_name || "N/A",
      mother_name: mother_name || "N/A",
      dob: dob || "1995-01-01",
      age: ageComputed,
      nid,
      phone,
      email: email || "",
      address: address || "N/A",
      category,
      experience: experience || "Fresher",
      skills: skills || "",
      photo: photo || "https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&q=80&w=400",
      documents: documents || "NID Verification pending",
      status: status || "approved", // Directly approved if configured
      created_at: new Date().toISOString(),
      helper_type,
      security_type,
      location: location || "Dhaka",
      vehicle_type,
      vehicle_photo: vehicle_photo || "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=600",
      route,
      capacity: capacity ? Number(capacity) : undefined,
      schedule,
      area: area || location || "Dhaka",
      description: description || ""
    };

    const saved = db.addApplicant(newApplicant);

    db.addActivityLog({
      id: "log_" + Math.random().toString(36).substr(2, 9),
      user_id: req.user!.id,
      user_name: req.user!.name,
      action: `Admin manually added candidate: ${full_name} (${category}) with status ${newApplicant.status}`,
      created_at: new Date().toISOString()
    });

    res.status(201).json({ success: true, applicant: saved });
  } catch (error) {
    res.status(500).json({ error: "Failed to manually register applicant." });
  }
});

// 8. SMTP Connection Handshake Diagnostic Test Route
app.post("/api/admin/test-smtp", authenticateToken, requireRole(["super_admin", "admin"]), async (req: AuthenticatedRequest, res: Response) => {
  try {
    const { smtp_host, smtp_port, smtp_secure, smtp_user, smtp_pass, smtp_sender_name, smtp_sender_email, test_recipient } = req.body;
    
    if (!smtp_host || !smtp_user || !smtp_pass || !test_recipient) {
      res.status(400).json({ error: "Host, User, Password, and Test Recipient elements are required." });
      return;
    }
    
    const port = Number(smtp_port) || 587;
    const secure = smtp_secure ?? (port === 465);
    
    const testTransporter = nodemailer.createTransport({
      host: smtp_host,
      port,
      secure,
      auth: { user: smtp_user, pass: smtp_pass },
      tls: { rejectUnauthorized: false }
    });
    
    await testTransporter.verify();
    
    await testTransporter.sendMail({
      from: `"${smtp_sender_name || "Manpower Portal Test"}" <${smtp_sender_email || "noreply@exprogroupbd.com"}>`,
      to: test_recipient,
      subject: "🔔 Nirapotta & Seba Admin Panel: Active SMTP Test Successful!",
      html: `
        <div style="font-family: Arial, sans-serif; border: 2px solid #10b981; border-radius: 8px; padding: 24px; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #10b981; margin-top: 0;">🎉 SMTP Handshake Succeeded!</h2>
          <p>Your mail delivery configuration was verified and accepted by the server successfully.</p>
          <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 16px 0;" />
          <ul style="padding-left: 20px; line-height: 1.8;">
            <li><strong>SMTP Server Host:</strong> ${smtp_host}</li>
            <li><strong>Port:</strong> ${port} (Secure: ${String(secure)})</li>
            <li><strong>Handshake User:</strong> ${smtp_user}</li>
            <li><strong>Handshake Timestamp:</strong> ${new Date().toLocaleString()}</li>
          </ul>
          <p style="font-size: 12px; color: #64748b; margin-top: 20px;">This verified handshake qualifies your server for delivering automated notifications upon registrations, settings edits, and security warning alerts.</p>
        </div>
      `
    });
    
    res.json({ success: true, message: "SMTP Server handshake verified and test notification broadcasted successfully!" });
  } catch (err: any) {
    res.status(500).json({ error: err.message || "Failed to establish secure TLS handshake to SMTP service." });
  }
});


/* ==========================================================================
   DEVELOPMENT & PRODUCTION FRONTEND INTEGRATION (Vite Middleware Setup)
   ========================================================================== */

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const { createServer: createViteServer } = await import("vite");
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
    console.log("Registered Dev Mode: Vite live middleware is mounted.");
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
    console.log("Registered Prod Mode: serving static generated assets from 'dist'");
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server actively running on host 0.0.0.0, port ${PORT}`);
  });
}

startServer();
